CREATE SCHEMA IF NOT EXISTS ONLINE_STORE;

CREATE SEQUENCE IF NOT EXISTS ONLINE_STORE.USER_ID_SEQ INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS ONLINE_STORE.GROUP_ID_SEQ INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS ONLINE_STORE.ROLE_ID_SEQ INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;

CREATE TABLE IF NOT EXISTS ONLINE_STORE.USERS(ID_USER bigint DEFAULT nextval('ONLINE_STORE.USER_ID_SEQ') PRIMARY KEY, LOGIN_USER text NOT NULL, PASSWORD_USER text NOT NULL);
CREATE TABLE IF NOT EXISTS ONLINE_STORE.GROUPS(ID_GROUP bigint DEFAULT nextval('ONLINE_STORE.GROUP_ID_SEQ') PRIMARY KEY, NAME_GROUP text NOT NULL);
CREATE TABLE IF NOT EXISTS ONLINE_STORE.ROLES(ID_ROLE bigint DEFAULT nextval('ONLINE_STORE.ROLE_ID_SEQ') PRIMARY KEY, NAME_ROLE text NOT NULL);