CREATE SCHEMA IF NOT EXISTS AUTHORIZATION_MODULE;

CREATE SEQUENCE IF NOT EXISTS AUTHORIZATION_MODULE.USER_ID_SEQ INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS AUTHORIZATION_MODULE.GROUP_ID_SEQ INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS AUTHORIZATION_MODULE.ROLE_ID_SEQ INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;

CREATE TABLE IF NOT EXISTS AUTHORIZATION_MODULE.USERS(ID_USER bigint DEFAULT nextval('AUTHORIZATION_MODULE.USER_ID_SEQ') PRIMARY KEY, LOGIN_USER text NOT NULL, PASSWORD_USER text NOT NULL);
CREATE TABLE IF NOT EXISTS AUTHORIZATION_MODULE.GROUPS(ID_GROUP bigint DEFAULT nextval('AUTHORIZATION_MODULE.GROUP_ID_SEQ') PRIMARY KEY, NAME_GROUP text NOT NULL);
CREATE TABLE IF NOT EXISTS AUTHORIZATION_MODULE.ROLES(ID_ROLE bigint DEFAULT nextval('AUTHORIZATION_MODULE.ROLE_ID_SEQ') PRIMARY KEY, NAME_ROLE text NOT NULL);