INSERT INTO AUTHORIZATION_MODULE.USERS SELECT 1, 'admin', 'admin' WHERE NOT EXISTS (SELECT ID_USER FROM AUTHORIZATION_MODULE.USERS WHERE ID_USER = 1);
INSERT INTO AUTHORIZATION_MODULE.USERS SELECT 2, 'test', 'test' WHERE NOT EXISTS (SELECT ID_USER FROM AUTHORIZATION_MODULE.USERS WHERE ID_USER = 2);

INSERT INTO AUTHORIZATION_MODULE.GROUPS SELECT 1, 'administrators' WHERE NOT EXISTS (SELECT ID_GROUP FROM AUTHORIZATION_MODULE.GROUPS WHERE ID_GROUP = 1);
INSERT INTO AUTHORIZATION_MODULE.GROUPS SELECT 2, 'users' WHERE NOT EXISTS (SELECT ID_GROUP FROM AUTHORIZATION_MODULE.GROUPS WHERE ID_GROUP = 2);

INSERT INTO AUTHORIZATION_MODULE.ROLES SELECT 1, 'administrator' WHERE NOT EXISTS (SELECT ID_ROLE FROM AUTHORIZATION_MODULE.ROLES WHERE ID_ROLE = 1);
INSERT INTO AUTHORIZATION_MODULE.ROLES SELECT 2, 'user' WHERE NOT EXISTS (SELECT ID_ROLE FROM AUTHORIZATION_MODULE.ROLES WHERE ID_ROLE = 2);

INSERT INTO AUTHORIZATION_MODULE.USER_GROUP SELECT 1, 1 WHERE NOT EXISTS (SELECT USER_GROUP.ID_USER FROM AUTHORIZATION_MODULE.USER_GROUP WHERE ID_USER = 1 AND ID_GROUP = 1);
INSERT INTO AUTHORIZATION_MODULE.USER_GROUP SELECT 2, 2 WHERE NOT EXISTS (SELECT USER_GROUP.ID_USER FROM AUTHORIZATION_MODULE.USER_GROUP WHERE ID_USER = 2 AND ID_GROUP = 2);

INSERT INTO AUTHORIZATION_MODULE.GROUP_ROLE SELECT 1, 1 WHERE NOT EXISTS (SELECT GROUP_ROLE.ID_GROUP FROM AUTHORIZATION_MODULE.GROUP_ROLE WHERE ID_GROUP = 1 AND ID_ROLE = 1);
INSERT INTO AUTHORIZATION_MODULE.GROUP_ROLE SELECT 2, 2 WHERE NOT EXISTS (SELECT GROUP_ROLE.ID_GROUP FROM AUTHORIZATION_MODULE.GROUP_ROLE WHERE ID_GROUP = 2 AND ID_ROLE = 2);