INSERT INTO AUTHORIZATION_MODULE.USERS VALUES(1, 'admin', '1');
INSERT INTO AUTHORIZATION_MODULE.USERS VALUES(2, 'test', 'test');

INSERT INTO AUTHORIZATION_MODULE.GROUPS VALUES(1, 'administrators');
INSERT INTO AUTHORIZATION_MODULE.GROUPS VALUES(2, 'users');

INSERT INTO AUTHORIZATION_MODULE.ROLES VALUES(1, 'administrator');
INSERT INTO AUTHORIZATION_MODULE.ROLES VALUES(2, 'user');

INSERT INTO AUTHORIZATION_MODULE.USER_GROUP VALUES(1, 1);
INSERT INTO AUTHORIZATION_MODULE.USER_GROUP VALUES(2, 2);

INSERT INTO AUTHORIZATION_MODULE.GROUP_ROLE VALUES(1, 1);
INSERT INTO AUTHORIZATION_MODULE.GROUP_ROLE VALUES(2, 2);