CREATE SCHEMA IF NOT EXISTS ONLINE_STORE;

CREATE SEQUENCE IF NOT EXISTS ONLINE_STORE.CATEGORIES_ID_SEQ INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;

CREATE TABLE IF NOT EXISTS ONLINE_STORE.CATEGORIES(ID_CATEGORY bigint DEFAULT nextval('ONLINE_STORE.CATEGORIES_ID_SEQ') NOT NULL PRIMARY KEY, NAME_CATEGORY text NOT NULL, DESCRIPTION_CATEGORY text);

CREATE TABLE IF NOT EXISTS ONLINE_STORE.OFFERS(ID_OFFER bigint NOT NULL PRIMARY KEY, NAME_OFFER text NOT NULL, DESCRIPTION_OFFER text, PRICE_OFFER real NOT NULL, ID_CATEGORY bigint  REFERENCES ONLINE_STORE.CATEGORIES);