CREATE SCHEMA IF NOT EXISTS CATALOG_SERVICE;

CREATE SEQUENCE IF NOT EXISTS CATALOG_SERVICE.CATEGORIES_ID_SEQ INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;

CREATE TABLE IF NOT EXISTS CATALOG_SERVICE.CATEGORIES(ID_CATEGORY bigint DEFAULT nextval('CATALOG_SERVICE.CATEGORIES_ID_SEQ') PRIMARY KEY, NAME_CATEGORY text NOT NULL, DESCRIPTION_CATEGORY text);
CREATE TABLE IF NOT EXISTS CATALOG_SERVICE.OFFERS(ID_OFFER bigint PRIMARY KEY, NAME_OFFER text NOT NULL, DESCRIPTION_OFFER text, PRICE_OFFER real NOT NULL, ID_CATEGORY bigint REFERENCES CATALOG_SERVICE.CATEGORIES);